DEFAULT_POLLING_INTERVAL = 5

# SMBus
DEFAULT_SMBUS_PORT = 1
DEFAULT_SMBUS_ADDR = 0x77

# 1-Wire
ONEWIRE_BASEDIR = '/sys/bus/w1/devices/'

# Measurements Retry
MEASUREMENTS_RETRY_MAX = 5
MEASUREMENTS_RETRY_INTERVAL = 0.25
